server:
   port: 8801
spring:
   application:
      name: server-config
   cloud:
      config:
         server:
            git: # 配置git
               uri: https://github.com/garyhu1/spring-cloud-config-repo
               # 采用占位符来配置git URI
               #uri: https://github.com/garyhu1/{application}
               username:
               password: 